// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1oeYvAFCltD0L-NhQLZXsZlzRvmABIds',
    appId: '1:567938947764:web:34e6275ef5c542b75315e1',
    messagingSenderId: '567938947764',
    projectId: 'bioliminal',
    authDomain: 'bioliminal.firebaseapp.com',
    storageBucket: 'bioliminal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsL7KLw1MwEopNG3R2sZEjvbsdrktYeiM',
    appId: '1:567938947764:android:ba6fb50e2357c63e5315e1',
    messagingSenderId: '567938947764',
    projectId: 'bioliminal',
    storageBucket: 'bioliminal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRlaf_8PUYpiRqqdPw4VIgxQU4L3BhPqM',
    appId: '1:567938947764:ios:ddebc788ea471e055315e1',
    messagingSenderId: '567938947764',
    projectId: 'bioliminal',
    storageBucket: 'bioliminal.firebasestorage.app',
    iosBundleId: 'com.bioliminal.app',
  );

}