// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8q1jQLraMrG8_FJDQ-_aUtD1EJqGQ8_E',
    appId: '1:975155858919:web:ee95c3051f912179d30142',
    messagingSenderId: '975155858919',
    projectId: 'bioliminal-capstone',
    authDomain: 'bioliminal-capstone.firebaseapp.com',
    storageBucket: 'bioliminal-capstone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4jqA9GEAGsaWyWf4KxVz-f7fzF2DGUWY',
    appId: '1:975155858919:android:0162cfd1f28bddf7d30142',
    messagingSenderId: '975155858919',
    projectId: 'bioliminal-capstone',
    storageBucket: 'bioliminal-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcIdEbPXR5vZ-D6WEkFqpUiqt3mu8OSQ0',
    appId: '1:975155858919:ios:5aed60dcb7609310d30142',
    messagingSenderId: '975155858919',
    projectId: 'bioliminal-capstone',
    storageBucket: 'bioliminal-capstone.firebasestorage.app',
    iosBundleId: 'com.bioliminal.bioliminal',
  );
}
